export default (req, res) => {
    const {
        query: { slug },
    } = req

    const pageno = slug[1];

    const content = {
        book: [
            {
                'bookUserName': 'finish',
                'pages': [
                    { no: '0', title: 'Nothing in life is perfect, and the real work of finishing a project begins after the first sign of imperfection.', text: 'I quit once it stopped being perfect, (Perfectionism) \n \n If we limit ourselves to perfect work, we’d never accomplish anything!\n\nHow you deal with these imperfections, and how you proceed once they arrive, is what determines your success in meeting goals.\n\nit’s the actions on the day after something went wrong that separate the quitters from the achievers. \nThe day after imperfections like these are when you need to accept that life is messy, and push on with your goals. Don’t fool yourself into thinking that excellence can only be achieved through perfection when, in reality, perfectionism is the killer of excellence' },
                    { no: '1', title: 'Avoid being overambitious, and increase your likelihood of finishing by cutting goals in half.', text: 'The concept of planning fallacy was pioneered by psychologists Daniel Kahneman and Amos Tversky. They found that people typically reveal a bias toward optimism by constantly underestimating how much time a task will take to complete.\n A reliable way to avoid both planning fallacy and perfectionism is to cut your goal in half. This will greatly reduce the chance of quitting due to being overwhelmed or biting off more than you can chew.' },
                    { no: '2', title: 'Reduce pressure by letting yourself be bad at some things.', text: 'No one enjoys producing bad work, but sometimes letting yourself be lousy at one thing allows you to finish more important work.\nThis brings us to the next pitfall of productivity: thinking that we need to be great at everything, when in fact it’s beneficial to be bad at some things.\nyou need to practice strategic incompetence; admit that you don’t have time to do everything and let things go, or give it the minimum amount of effort required.' },
                    { no: '3', title: 'You’ll get more done when it’s fun.', text: 'You would certainly be better off enjoying the work you do, since you’re more likely to achieve your goals if they involve something you like doing \n two decisive factors in setting a goal are satisfaction and performance success.\n look at this is through a simple equation: fun = success. We don’t always get to pick our goals, but we can often turn them into work that is fun. \n You can think up prizes to add at the end of every week when short-term goals are reached, \n Deadlines can also be turned into a fun motivator. A lot of people dread deadlines, but they also provide a certain rush. So, instead of one monthly or weekly deadline, you can set up multiple deadlines every day to get that recurring thrill that keeps you going.' },
                    { no: '4', title: 'Identify your own perfectionist rules and find your true motivations.', text: 'One of the biggest lies related to perfectionism is that perfection is attainable if we follow certain r\n Now, these rules can vary from person to person, and they can make it impossible for people to finish their projects, so it’s helpful to figure out your own perfectionist rule.\n “If something is easy, it can’t be worth doing,” and “If it’s not successful in ten days, it’s a failure.”\n “What do I really want?”\n focus away from perfectionism and start getting good results.' },
                    { no: '5', title: 'Avoid last-minute pitfalls that play into your fear of failure.', text: 'If you’ve gotten this far, you might think it’s smooth sailing from here, right? Not so fast. Perfectionism will strike once more, on the day before \n One of the tricks of perfectionism is to think ahead to “what-if” scenarios, and as the finish line draws near, these thoughts can turn to fears that will cause you to stumble right before the end. If you’re writing a book, you might be nearing the end and start thinking, “What if the critics hate it? What if no one buys it?”\n Stephen King once said, “People are extremely hard to live with when they have a talent they aren’t able to use.”\n instead of playing “what-if” games, see what happens – and don’t waste time and energy worrying about things that haven’t happened yet.\n Be honest about your motivations, and if this kind of situation applies to you, it’s probably time to reassess your fears and rewards, so that you can give yourself that final push to finish. \n no external praise will compare to the personal joy and satisfaction you’ll get when you follow through and keep the promises you’ve made to yourself.' }
                ]
            },
            {
                'bookUserName': 'micromastery',
                'pages': [
                    { no: '0', title: 'What’s in it for me? Discover how to master any skill.', text: 'When it comes to learning a new skill or diving into a new hobby, most of us are dissuaded by the amount of time and effort such tasks require. That’s where micromastery can help.\n Micromastery aims to eliminate the phenomenon of demotivation, which can often stand in the way of success. By breaking up a goal into small, achievable stages, micromastery encourages you to focus on a specific skill before moving onto the next one. The sense of accomplishment you feel from completing each stage will motivate you to keep going until you finally achieve your bigger goal.' },
                    { no: '1', title: 'Micromastery helps you and your brain get in great shape.', text: 'Micromastery is a mental workout. Our brains are constantly changing, and if we don’t give them exercise by learning new things, we will fail to forge new neural connections that allow us to perform tasks. Indeed, we could end up forgetting how to do something if we allow our neural pathways to become weakened through inacti\nMicromastery also helps facilitate a polymathic lifestyle, meaning a lifestyle that involves continuously learning many different skills. And that’s great because there’s a neurological advantage to being a polymath. If we go through our lives on autopilot and stop learning and challenging ourselves with different mental stimuli, our cognitive abilities will begin to degrade. Over time, this can lead to senility.\nthe brain is fed varied and multisensory input that keeps it in good shape.' },
                    { no: '2', title: 'Micromastery consists of six elements; the first three involve an entry trick, a rub-pat barrier and background support.', text: 'First, every micromastery involves an entry trick, which is a cunning scheme that speeds up your performance and pays off immedia\n Second, micromasteries each have a rub-pat barrier, which is the obstacle that arises when two required skills are incongruent with each other.\n To defeat this barrier, it is necessary to focus on each skill individually; eventually, it’ll become easier to do both at once.\n The third element of micromastery is background support, which clears your path of any roadblocks.\n To make this point more concrete, let’s look at drawing. Say you want to learn how to draw perfect Zen circles, which is the special Japanese technique of drawing circles in one brushstroke, or two at most. What will help you achieve this skill is a really nice pen, one that makes you feel good using it – this could be a fiber-tip pen or a brush pen, or any other pen that can produce clean brushstrokes.' },
                    { no: '3', title: 'The other three elements of micromastery are payoff, repeatability and experimentation.', text: 'The next element of micromastery is repeatability. If you can replicate a micromastery over and over again, you will be able to see your improvements with each repetition, increasing your confid\n The sixth and final element of micromastery is experimentation. Experimentation enables you to play around with the skill or task you’re trying to learn, which prevents the process from becoming tedious. Furthermore, it maintains your curiosity, which helps expand your desire for further knowledge and involvement with the task at hand.\n Experiences like that illustrate why there has to be a payoff that will encourage you to keep putting in effort. If you feel like you’re getting better at something, that feeling of success will make you want to continue.' }
                ]
            }, {
                'bookUserName': 'get-your-sht-together',
                'pages': [
                    { no: '0', title: 'Get your shit together by allocating time to achieve realistic goals.', text: '“I just don’t know where to begin.” If this sounds familiar, then the first step toward getting your shit together is to consider exactly what your goals are, and when you plan to achieve them.\n This is problematic because we can’t become winners if we’re constantly holding ourselves to unrealistic standards.' },
                    { no: '1', title: 'Get your shit together by ditching your unrealistic goals.', text: 'If you feel as if you don’t have enough time to meet your goals, you probably have bad time-management skills. Combat this problem by gaining a better understanding of how you actually spend your time. You can do this by timing how long it takes you to fulfill routine tasks. \nThen, use this knowledge to create a realistic weekly schedule that contains all the things you want to do but never seem to have time for, such as learning a new skill.' },
                    { no: '2', title: 'Get your professional shit together by exuding confidence and asking the right questions.', text: 'When it comes to the world of work, appearing confident – even if on the inside you’re anything but – is crucial if you’re going to win the trust and respect of others. \n Another important way to get your professional shit together is to ask your boss the right questions.' },
                    { no: '3', title: 'Get your health on track by prioritizing and by harnessing the power of negative thinking.', text: 'Your physical health goals also don’t need to be radical for them to count toward getting your shit together.' },
                    { no: '4', title: 'Cope with anxiety by being proactive or by strategically doing nothing.', text: 'Sometimes the best strategy when dealing with anxiety-inducing situations is to face the situation head-on and rip off that anxiety Band-Aid. \n The second strategy for coping with anxiety is precisely the opposite of the first. Instead of being proactive, consciously decide to do nothing. In this strategy, you ignore the situation and hope that any problems resolve themselves on their own. This may sound irresponsible, but it’s just sensible hesitation.' },
                    { no: '5', title: 'Get house proud by dividing chores into 20-minute sessions.', text: 'The first step is to undertake a one-off decluttering session. \n Once you’re satisfied with your efforts, the next step is to make a plan for the long-term tidiness. \n Now that you have divided all your chores into categories, it’s time to commit to getting your shit together by making a pledge to yourself.' }
                ]
            }
        ]
    }

    var reqContent = content.book.filter((book) => (book.bookUserName === slug[0]))[0];

    res.json(reqContent.pages[pageno])
}